// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ParcelNumberGenerator.Data;

#nullable disable

namespace ParcelNumberGenerator.Migrations.PostgreSQL.Migrations
{
    [DbContext(typeof(ParcelNumbersDbContext))]
    [Migration("20260815091518_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ParcelNumberGenerator.Data.UsedNumber", b =>
                {
                    b.Property<int>("Number")
                        .HasColumnType("integer")
                        .HasColumnName("number");

                    b.Property<DateTimeOffset>("AllocatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("allocated_at_utc");

                    b.HasKey("Number");

                    b.ToTable("used_numbers", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
