// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ParcelNumberGenerator.Data;

#nullable disable

namespace ParcelNumberGenerator.Migrations.SqlServer.Migrations
{
    [DbContext(typeof(ParcelNumbersDbContext))]
    partial class ParcelNumbersDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ParcelNumberGenerator.Data.UsedNumber", b =>
                {
                    b.Property<int>("Number")
                        .HasColumnType("int")
                        .HasColumnName("number");

                    b.Property<DateTimeOffset>("AllocatedAtUtc")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("allocated_at_utc");

                    b.HasKey("Number");

                    b.ToTable("used_numbers", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
